server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://${EUREKA:localhost}:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: provserv
          uri: lb://provserv
          predicates:
            - Path=/proveedor/**
        - id: acoserv
          uri: lb://acoserv
          predicates:
            - Path=/acopio/**
        - id: calserv
          uri: lb://calserv
          predicates:
            - Path=/calidad/**
        - id: pagoserv
          uri: lb://pagoserv
          predicates:
            - Path=/pago/**