apiVersion: v1
kind: Service
metadata:
  name: calidad-service
  labels:
    app: calidad-service
spec:
  selector:
    app: calidad-deployment
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: NodePort