apiVersion: apps/v1
kind: Deployment
metadata:
  name: acopio-deployment
  labels:
    app: acopio-deployment
spec:
  selector:
    matchLabels:
      app: acopio-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: acopio-deployment
    spec:
      containers:
        - name: acopio-service
          image: negherch/kubernetes-acopio
          ports:
            - containerPort: 8083
          env:
            - name: spring.cloud.config.uri
              value: http://config-service:8081
            - name: spring.config.import
              value: optional:configserver:http://config-service:8081
            - name: eureka.client.serviceUrl.defaultZone
              value: http://eureka-service:8761
            - name: EUREKA
              value: eureka-service
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-acopios:5432/acopios
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-db
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-db
                  key: name4
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-user-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-user-credentials
                  key: password